#!/usr/bin/env python3

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path
from typing import Any


DEFAULT_RECALL_KS = [1, 2, 4, 5, 10, 20, 50, 100]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Evaluate page retrieval against pseudo page labels stored in an augmented "
            "MMQA/M3DocVQA gold JSONL, typically metadata.gold_page_uids generated by "
            "build_mmqa_pseudo_page_labels.py."
        )
    )
    parser.add_argument("--gold", required=True, help="Augmented MMQA JSONL with pseudo page labels.")
    parser.add_argument(
        "--run",
        action="append",
        required=True,
        help="Prediction run as LABEL=path/to/prediction.json. Can be repeated.",
    )
    parser.add_argument(
        "--group",
        action="append",
        default=[],
        help="Optional qid group as GROUP=path/to/qids.txt. Can be repeated. Defaults to all qids.",
    )
    parser.add_argument("--recall-k", type=int, nargs="+", default=DEFAULT_RECALL_KS)
    parser.add_argument("--hit-k", type=int, default=4, help="Cutoff for movement counts vs first run.")
    parser.add_argument("--format", choices=["markdown", "csv", "json"], default="markdown")
    parser.add_argument("--output", default="", help="Optional output file. Prints to stdout if omitted.")
    return parser.parse_args()


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def load_gold(path: Path) -> dict[str, dict[str, Any]]:
    out: dict[str, dict[str, Any]] = {}
    for row in load_jsonl(path):
        qid = str(row.get("qid", "")).strip()
        if qid:
            out[qid] = row
    return out


def parse_labeled_path(spec: str) -> tuple[str, Path]:
    if "=" not in spec:
        raise ValueError(f"Expected LABEL=path, got {spec!r}")
    label, raw_path = spec.split("=", 1)
    label = label.strip()
    path = Path(raw_path.strip())
    if not label or not str(path):
        raise ValueError(f"Invalid run spec: {spec!r}")
    return label, path


def load_prediction(path: Path) -> dict[str, dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(payload, dict) and isinstance(payload.get("predictions"), (dict, list)):
        payload = payload["predictions"]
    if isinstance(payload, dict):
        iterator = payload.items()
    elif isinstance(payload, list):
        iterator = enumerate(payload)
    else:
        raise TypeError(f"Prediction JSON must be object or list: {path}")
    out: dict[str, dict[str, Any]] = {}
    for raw_key, row in iterator:
        if not isinstance(row, dict):
            continue
        qid = str(row.get("qid") or raw_key).strip()
        if qid:
            out[qid] = row
    return out


def load_groups(specs: list[str], gold: dict[str, dict[str, Any]]) -> dict[str, set[str]]:
    if not specs:
        return {"all": set(gold)}
    groups: dict[str, set[str]] = {}
    for spec in specs:
        if "=" not in spec:
            raise ValueError(f"Expected GROUP=path, got {spec!r}")
        name, raw_path = spec.split("=", 1)
        path = Path(raw_path.strip())
        qids = {line.strip() for line in path.read_text(encoding="utf-8").splitlines() if line.strip()}
        groups[name.strip()] = qids
    return groups


def page_uid(doc_id: str, page_idx: int) -> str:
    return f"{doc_id}_page{int(page_idx)}"


def parse_page_uid(uid: str) -> tuple[str, int] | None:
    if "_page" not in uid:
        return None
    doc_id, raw_page = uid.rsplit("_page", 1)
    if not doc_id:
        return None
    try:
        return doc_id, int(raw_page)
    except ValueError:
        return None


def parse_prediction_row(row: Any) -> tuple[str, int, float | None] | None:
    if isinstance(row, (list, tuple)) and len(row) >= 2:
        doc_id = str(row[0]).strip()
        if not doc_id:
            return None
        try:
            page_idx = int(row[1])
        except (TypeError, ValueError):
            return None
        score: float | None = None
        if len(row) >= 3 and row[2] is not None:
            try:
                score = float(row[2])
            except (TypeError, ValueError):
                score = None
        return doc_id, page_idx, score
    if isinstance(row, dict):
        uid = str(row.get("page_uid", "")).strip()
        if uid:
            parsed = parse_page_uid(uid)
            if parsed is None:
                return None
            doc_id, page_idx = parsed
        else:
            doc_id = str(row.get("doc_id", row.get("docid", row.get("document_id", "")))).strip()
            page_value = row.get("page_idx", row.get("page_id", row.get("page")))
            if not doc_id or page_value is None:
                return None
            try:
                page_idx = int(page_value)
            except (TypeError, ValueError):
                return None
        score_value = row.get("score", row.get("retrieval_score", row.get("fused_page_score")))
        score = None
        if score_value is not None:
            try:
                score = float(score_value)
            except (TypeError, ValueError):
                score = None
        return doc_id, page_idx, score
    return None


def prediction_rows(row: dict[str, Any] | None) -> list[Any]:
    if not isinstance(row, dict):
        return []
    rows = row.get("page_retrieval_results", row.get("retrieval_results", row.get("results", [])))
    return rows if isinstance(rows, list) else []


def ranked_pages(pred_row: dict[str, Any] | None) -> list[str]:
    pages: list[str] = []
    seen: set[str] = set()
    for row in prediction_rows(pred_row):
        parsed = parse_prediction_row(row)
        if parsed is None:
            continue
        uid = page_uid(parsed[0], parsed[1])
        if uid in seen:
            continue
        seen.add(uid)
        pages.append(uid)
    return pages


def ranked_docs_from_pages(pages: list[str]) -> list[str]:
    docs: list[str] = []
    seen: set[str] = set()
    for uid in pages:
        parsed = parse_page_uid(uid)
        doc_id = parsed[0] if parsed is not None else uid
        if doc_id in seen:
            continue
        seen.add(doc_id)
        docs.append(doc_id)
    return docs


def gold_pages(row: dict[str, Any]) -> set[str]:
    metadata = row.get("metadata", {}) if isinstance(row.get("metadata"), dict) else {}
    values = (
        metadata.get("gold_page_uids")
        or metadata.get("pseudo_gold_page_uids")
        or row.get("gold_page_uids")
        or row.get("pseudo_gold_page_uids")
        or []
    )
    return {str(value).strip() for value in values if str(value).strip()}


def gold_docs_from_pages(pages: set[str]) -> set[str]:
    docs: set[str] = set()
    for uid in pages:
        parsed = parse_page_uid(uid)
        if parsed is not None:
            docs.add(parsed[0])
    return docs


def first_rank(ranked: list[str], gold: set[str]) -> int | None:
    for idx, item in enumerate(ranked, start=1):
        if item in gold:
            return idx
    return None


def hit_at(ranked: list[str], gold: set[str], k: int) -> bool:
    return bool(gold and any(item in gold for item in ranked[: int(k)]))


def reciprocal_rank(rank: int | None) -> float:
    return 0.0 if rank is None else 1.0 / float(rank)


def summarize_run(
    *,
    group: str,
    label: str,
    gold: dict[str, dict[str, Any]],
    qids: set[str],
    pred: dict[str, dict[str, Any]],
    recall_ks: list[int],
) -> dict[str, Any]:
    page_hits = {k: 0 for k in recall_ks}
    doc_hits = {k: 0 for k in recall_ks}
    page_mrr = 0.0
    doc_mrr = 0.0
    n_eval = 0
    skipped_no_page_gold = 0
    missing_prediction = 0
    for qid in sorted(qids):
        row = gold.get(qid)
        if row is None:
            continue
        gp = gold_pages(row)
        if not gp:
            skipped_no_page_gold += 1
            continue
        gd = gold_docs_from_pages(gp)
        pred_row = pred.get(qid)
        if pred_row is None:
            missing_prediction += 1
            continue
        pages = ranked_pages(pred_row)
        docs = ranked_docs_from_pages(pages)
        n_eval += 1
        page_mrr += reciprocal_rank(first_rank(pages, gp))
        doc_mrr += reciprocal_rank(first_rank(docs, gd))
        for k in recall_ks:
            if hit_at(pages, gp, k):
                page_hits[k] += 1
            if hit_at(docs, gd, k):
                doc_hits[k] += 1
    out: dict[str, Any] = {
        "group": group,
        "label": label,
        "n_eval": n_eval,
        "skipped_no_page_gold": skipped_no_page_gold,
        "missing_prediction": missing_prediction,
        "page_mrr": page_mrr / float(n_eval) if n_eval else 0.0,
        "doc_mrr": doc_mrr / float(n_eval) if n_eval else 0.0,
    }
    for k in recall_ks:
        out[f"page@{k}"] = page_hits[k] / float(n_eval) if n_eval else 0.0
        out[f"doc@{k}"] = doc_hits[k] / float(n_eval) if n_eval else 0.0
    return out


def movement_vs_baseline(
    *,
    gold: dict[str, dict[str, Any]],
    qids: set[str],
    baseline: dict[str, dict[str, Any]],
    candidate: dict[str, dict[str, Any]],
    hit_k: int,
) -> dict[str, Any]:
    improved_rank = 0
    worsened_rank = 0
    unchanged = 0
    recovered = 0
    lost = 0
    for qid in sorted(qids):
        row = gold.get(qid)
        if row is None:
            continue
        gp = gold_pages(row)
        if not gp:
            continue
        base_rank = first_rank(ranked_pages(baseline.get(qid)), gp)
        cand_rank = first_rank(ranked_pages(candidate.get(qid)), gp)
        base_hit = base_rank is not None and base_rank <= int(hit_k)
        cand_hit = cand_rank is not None and cand_rank <= int(hit_k)
        if base_hit and not cand_hit:
            lost += 1
        elif not base_hit and cand_hit:
            recovered += 1
        if base_rank == cand_rank:
            unchanged += 1
        elif cand_rank is None:
            worsened_rank += 1
        elif base_rank is None or cand_rank < base_rank:
            improved_rank += 1
        else:
            worsened_rank += 1
    return {
        "improved_rank": improved_rank,
        "worsened_rank": worsened_rank,
        "unchanged": unchanged,
        f"recovered@{hit_k}": recovered,
        f"lost@{hit_k}": lost,
        f"net@{hit_k}": recovered - lost,
    }


def build_rows(args: argparse.Namespace) -> list[dict[str, Any]]:
    gold = load_gold(Path(args.gold))
    groups = load_groups(args.group, gold)
    runs = [(label, load_prediction(path)) for label, path in map(parse_labeled_path, args.run)]
    baseline_label, baseline_pred = runs[0]
    rows: list[dict[str, Any]] = []
    for group_name, qids in groups.items():
        for label, pred in runs:
            row = summarize_run(
                group=group_name,
                label=label,
                gold=gold,
                qids=qids,
                pred=pred,
                recall_ks=list(args.recall_k),
            )
            if label != baseline_label:
                row.update(
                    movement_vs_baseline(
                        gold=gold,
                        qids=qids,
                        baseline=baseline_pred,
                        candidate=pred,
                        hit_k=int(args.hit_k),
                    )
                )
            rows.append(row)
    return rows


def render_markdown(rows: list[dict[str, Any]], recall_ks: list[int], hit_k: int) -> str:
    headers = [
        "group",
        "label",
        "n_eval",
        "skipped_no_page_gold",
        "missing_prediction",
        "page_mrr",
        "doc_mrr",
        "improved_rank",
        "worsened_rank",
        f"recovered@{hit_k}",
        f"lost@{hit_k}",
        f"net@{hit_k}",
    ]
    for k in recall_ks:
        headers.extend([f"page@{k}", f"doc@{k}"])
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    for row in rows:
        values: list[str] = []
        for header in headers:
            value = row.get(header, "")
            if isinstance(value, float):
                values.append(f"{value:.4f}")
            else:
                values.append(str(value))
        lines.append("| " + " | ".join(values) + " |")
    return "\n".join(lines) + "\n"


def render_csv(rows: list[dict[str, Any]], recall_ks: list[int], hit_k: int) -> str:
    headers = [
        "group",
        "label",
        "n_eval",
        "skipped_no_page_gold",
        "missing_prediction",
        "page_mrr",
        "doc_mrr",
        "improved_rank",
        "worsened_rank",
        f"recovered@{hit_k}",
        f"lost@{hit_k}",
        f"net@{hit_k}",
    ]
    for k in recall_ks:
        headers.extend([f"page@{k}", f"doc@{k}"])
    from io import StringIO

    handle = StringIO()
    writer = csv.DictWriter(handle, fieldnames=headers, extrasaction="ignore")
    writer.writeheader()
    for row in rows:
        writer.writerow(row)
    return handle.getvalue()


def main() -> None:
    args = parse_args()
    rows = build_rows(args)
    if args.format == "json":
        text = json.dumps(rows, indent=2) + "\n"
    elif args.format == "csv":
        text = render_csv(rows, list(args.recall_k), int(args.hit_k))
    else:
        text = render_markdown(rows, list(args.recall_k), int(args.hit_k))
    if args.output:
        path = Path(args.output)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"saved_output={path}")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
