#!/usr/bin/env bash

if [[ -n "${M3DOCVQA_INTERNAL_ENV_LOADED:-}" ]]; then
  return 0 2>/dev/null || exit 0
fi
export M3DOCVQA_INTERNAL_ENV_LOADED=1

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"

PYTHON_BIN="${PYTHON_BIN:-$REPO_ROOT/env/bin/python}"
if [[ ! -x "$PYTHON_BIN" ]]; then
  PYTHON_BIN="${PYTHON_BIN_FALLBACK:-python}"
fi

ACCELERATE_BIN="${ACCELERATE_BIN:-$REPO_ROOT/env/bin/accelerate}"
if [[ ! -x "$ACCELERATE_BIN" ]]; then
  ACCELERATE_BIN="${ACCELERATE_BIN_FALLBACK:-accelerate}"
fi

DEFAULT_M3DOCVQA_LOCAL_DATA_DIR="$REPO_ROOT/data"
DEFAULT_M3DOCVQA_LOCAL_MODEL_DIR="$REPO_ROOT/model"
DEFAULT_M3DOCVQA_LOCAL_EMBEDDINGS_DIR="$REPO_ROOT/embeddings"
DEFAULT_M3DOCVQA_LOCAL_OUTPUT_DIR="$REPO_ROOT/output"

M3DOCVQA_LOCAL_DATA_DIR="${M3DOCVQA_LOCAL_DATA_DIR:-$DEFAULT_M3DOCVQA_LOCAL_DATA_DIR}"
M3DOCVQA_LOCAL_MODEL_DIR="${M3DOCVQA_LOCAL_MODEL_DIR:-$DEFAULT_M3DOCVQA_LOCAL_MODEL_DIR}"
M3DOCVQA_LOCAL_EMBEDDINGS_DIR="${M3DOCVQA_LOCAL_EMBEDDINGS_DIR:-$DEFAULT_M3DOCVQA_LOCAL_EMBEDDINGS_DIR}"
M3DOCVQA_LOCAL_OUTPUT_DIR="${M3DOCVQA_LOCAL_OUTPUT_DIR:-$DEFAULT_M3DOCVQA_LOCAL_OUTPUT_DIR}"

export LOCAL_DATA_DIR="$M3DOCVQA_LOCAL_DATA_DIR"
export LOCAL_MODEL_DIR="$M3DOCVQA_LOCAL_MODEL_DIR"
export LOCAL_EMBEDDINGS_DIR="$M3DOCVQA_LOCAL_EMBEDDINGS_DIR"
export LOCAL_OUTPUT_DIR="$M3DOCVQA_LOCAL_OUTPUT_DIR"

DATA_NAME="${DATA_NAME:-m3-docvqa}"
SPLIT="${SPLIT:-dev}"
DATASET_ROOT="${DATASET_ROOT:-$M3DOCVQA_LOCAL_DATA_DIR/$DATA_NAME}"
GOLD="${GOLD:-$DATASET_ROOT/multimodalqa/MMQA_${SPLIT}.jsonl}"

RETRIEVAL_MODEL_TYPE="${RETRIEVAL_MODEL_TYPE:-colpali}"
RETRIEVAL_MODEL_NAME="${RETRIEVAL_MODEL_NAME:-colpaligemma-3b-pt-448-base}"
RETRIEVAL_ADAPTER_MODEL_NAME="${RETRIEVAL_ADAPTER_MODEL_NAME:-colpali-v1.2}"
EMBEDDING_NAME="${EMBEDDING_NAME:-${RETRIEVAL_ADAPTER_MODEL_NAME}_${DATA_NAME}_${SPLIT}}"

FAISS_INDEX_TYPE="${FAISS_INDEX_TYPE:-ivfflat}"
FAISS_NPROBE="${FAISS_NPROBE:-4}"
INDEX_NAME="${INDEX_NAME:-${EMBEDDING_NAME}_pageindex_${FAISS_INDEX_TYPE}}"
QUESTION_TYPE_FILTER="${QUESTION_TYPE_FILTER:-}"

QIDS_OUT_DIR="${QIDS_OUT_DIR:-$LOCAL_OUTPUT_DIR/m3docvqa_qids}"
QIDS_JSONL="${QIDS_JSONL:-$QIDS_OUT_DIR/MMQA_${SPLIT}_qids.jsonl}"
