#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${REPO_ROOT:-$(cd "$SCRIPT_DIR/.." && pwd)}"
PYTHON_BIN="${PYTHON_BIN:-$REPO_ROOT/env/bin/python}"
if [[ ! -x "$PYTHON_BIN" ]]; then
  PYTHON_BIN="${PYTHON_BIN_FALLBACK:-python}"
fi

: "${DATA_NAME:?Set DATA_NAME, e.g. mmdocir, sciegqa, vidoseek, or vidore-v3}"
: "${DATA_ROOT:?Set DATA_ROOT to the converted dataset root}"
: "${DENSE_PRED:?Set DENSE_PRED to the dense/plain_top224 prediction JSON}"
: "${SPARSE_PRED:?Set SPARSE_PRED to the SPLADE prediction JSON}"
: "${OUT_DIR:?Set OUT_DIR for graph-PPR outputs}"

SPLIT="${SPLIT:-dev}"
GOLD="${GOLD:-$DATA_ROOT/MMQA_${SPLIT}.jsonl}"
GRAPH_PROFILE="${GRAPH_PROFILE:-doc_shortlist_best}"
case "$GRAPH_PROFILE" in
  doc_shortlist_best)
    DEFAULT_FINAL_TOP_PAGES=20
    DEFAULT_PER_DOC_PAGE_LIMIT=1
    DEFAULT_RESTART_PROB=0.15
    DEFAULT_FINAL_PPR_DOC_WEIGHT=0.75
    DEFAULT_RECALL_K_VALUES="1 2 4 5 10 20"
    ;;
  page_rank_probe)
    DEFAULT_FINAL_TOP_PAGES=1000
    DEFAULT_PER_DOC_PAGE_LIMIT=0
    DEFAULT_RESTART_PROB=0.20
    DEFAULT_FINAL_PPR_DOC_WEIGHT=0.5
    DEFAULT_RECALL_K_VALUES="1 2 4 5 10 20 50 100"
    ;;
  *)
    echo "Unsupported GRAPH_PROFILE=$GRAPH_PROFILE. Use doc_shortlist_best or page_rank_probe." >&2
    exit 1
    ;;
esac

GRAPH_LABEL="${GRAPH_LABEL:-${DATA_NAME}_plain_top224_splade_graph_ppr_${GRAPH_PROFILE}}"
PRED_OUT="${PRED_OUT:-$OUT_DIR/${GRAPH_LABEL}.prediction.json}"
SUMMARY_OUT="${SUMMARY_OUT:-$OUT_DIR/${GRAPH_LABEL}.summary.json}"

DENSE_TOP_PAGES="${DENSE_TOP_PAGES:-1000}"
SPARSE_TOP_PAGES="${SPARSE_TOP_PAGES:-1000}"
FINAL_TOP_PAGES="${FINAL_TOP_PAGES:-$DEFAULT_FINAL_TOP_PAGES}"
PER_DOC_PAGE_LIMIT="${PER_DOC_PAGE_LIMIT:-$DEFAULT_PER_DOC_PAGE_LIMIT}"
RRF_K="${RRF_K:-10}"
DENSE_WEIGHT="${DENSE_WEIGHT:-1.0}"
SPARSE_WEIGHT="${SPARSE_WEIGHT:-1.0}"
ADAPTIVE_SOURCE_WEIGHT_MODE="${ADAPTIVE_SOURCE_WEIGHT_MODE:-none}"
ADAPTIVE_SOURCE_AGREEMENT_TOP_PAGES="${ADAPTIVE_SOURCE_AGREEMENT_TOP_PAGES:-20}"
ADAPTIVE_SOURCE_TOP1_LOOKUP_PAGES="${ADAPTIVE_SOURCE_TOP1_LOOKUP_PAGES:-1000}"
ADAPTIVE_SOURCE_DOC_OVERLAP_WEIGHT="${ADAPTIVE_SOURCE_DOC_OVERLAP_WEIGHT:-0.7}"
ADAPTIVE_SOURCE_PAGE_OVERLAP_WEIGHT="${ADAPTIVE_SOURCE_PAGE_OVERLAP_WEIGHT:-0.2}"
ADAPTIVE_SOURCE_TOP1_WEIGHT="${ADAPTIVE_SOURCE_TOP1_WEIGHT:-0.1}"
ADAPTIVE_SOURCE_STRENGTH="${ADAPTIVE_SOURCE_STRENGTH:-0.5}"
ADAPTIVE_SOURCE_GAMMA="${ADAPTIVE_SOURCE_GAMMA:-1.0}"
ADAPTIVE_SOURCE_MIN_DENSE_MULT="${ADAPTIVE_SOURCE_MIN_DENSE_MULT:-1.0}"
ADAPTIVE_SOURCE_MAX_DENSE_MULT="${ADAPTIVE_SOURCE_MAX_DENSE_MULT:-1.5}"
ADAPTIVE_SOURCE_MIN_SPARSE_MULT="${ADAPTIVE_SOURCE_MIN_SPARSE_MULT:-0.5}"
ADAPTIVE_SOURCE_MAX_SPARSE_MULT="${ADAPTIVE_SOURCE_MAX_SPARSE_MULT:-1.0}"
ADAPTIVE_SOURCE_RECIPROCAL_TOP_PAGES="${ADAPTIVE_SOURCE_RECIPROCAL_TOP_PAGES:-20}"
ADAPTIVE_SOURCE_RECIPROCAL_LOOKUP_PAGES="${ADAPTIVE_SOURCE_RECIPROCAL_LOOKUP_PAGES:-1000}"
ADAPTIVE_SOURCE_RECIPROCAL_DOC_WEIGHT="${ADAPTIVE_SOURCE_RECIPROCAL_DOC_WEIGHT:-0.7}"
ADAPTIVE_SOURCE_RECIPROCAL_PAGE_WEIGHT="${ADAPTIVE_SOURCE_RECIPROCAL_PAGE_WEIGHT:-0.3}"
ADAPTIVE_SOURCE_RECIPROCAL_MIN_MULT="${ADAPTIVE_SOURCE_RECIPROCAL_MIN_MULT:-0.75}"
ADAPTIVE_SOURCE_RECIPROCAL_MAX_MULT="${ADAPTIVE_SOURCE_RECIPROCAL_MAX_MULT:-1.25}"
ADAPTIVE_SOURCE_RECIPROCAL_PRESERVE_TOTAL="${ADAPTIVE_SOURCE_RECIPROCAL_PRESERVE_TOTAL:-1}"
ADAPTIVE_RESTART_MODE="${ADAPTIVE_RESTART_MODE:-none}"
ADAPTIVE_RESTART_SOURCE_STRENGTH="${ADAPTIVE_RESTART_SOURCE_STRENGTH:-0.5}"
ADAPTIVE_RESTART_GAMMA="${ADAPTIVE_RESTART_GAMMA:-1.0}"
ADAPTIVE_RESTART_MIN_DENSE_MULT="${ADAPTIVE_RESTART_MIN_DENSE_MULT:-1.0}"
ADAPTIVE_RESTART_MAX_DENSE_MULT="${ADAPTIVE_RESTART_MAX_DENSE_MULT:-1.5}"
ADAPTIVE_RESTART_MIN_SPARSE_MULT="${ADAPTIVE_RESTART_MIN_SPARSE_MULT:-0.5}"
ADAPTIVE_RESTART_MAX_SPARSE_MULT="${ADAPTIVE_RESTART_MAX_SPARSE_MULT:-1.0}"
ADAPTIVE_RESTART_PAGE_SEED_WEIGHT="${ADAPTIVE_RESTART_PAGE_SEED_WEIGHT:-1.0}"
ADAPTIVE_RESTART_DOC_SEED_WEIGHT="${ADAPTIVE_RESTART_DOC_SEED_WEIGHT:-0.25}"
ADAPTIVE_RESTART_MIN_DOC_MULT="${ADAPTIVE_RESTART_MIN_DOC_MULT:-0.0}"
ADAPTIVE_RESTART_MAX_DOC_MULT="${ADAPTIVE_RESTART_MAX_DOC_MULT:-1.0}"
ADAPTIVE_RESTART_NEIGHBOR_SEED_WEIGHT="${ADAPTIVE_RESTART_NEIGHBOR_SEED_WEIGHT:-1.0}"
ADAPTIVE_RESTART_PRESERVE_SOURCE_TOTAL="${ADAPTIVE_RESTART_PRESERVE_SOURCE_TOTAL:-1}"
ADAPTIVE_TRANSITION_MODE="${ADAPTIVE_TRANSITION_MODE:-none}"
ADAPTIVE_TRANSITION_AGREEMENT_MIN_MULT="${ADAPTIVE_TRANSITION_AGREEMENT_MIN_MULT:-0.75}"
ADAPTIVE_TRANSITION_AGREEMENT_MAX_MULT="${ADAPTIVE_TRANSITION_AGREEMENT_MAX_MULT:-1.0}"
ADAPTIVE_TRANSITION_LOCAL_MIN_MULT="${ADAPTIVE_TRANSITION_LOCAL_MIN_MULT:-0.75}"
ADAPTIVE_TRANSITION_LOCAL_MAX_MULT="${ADAPTIVE_TRANSITION_LOCAL_MAX_MULT:-1.0}"
ADAPTIVE_TRANSITION_LOCAL_WEIGHT="${ADAPTIVE_TRANSITION_LOCAL_WEIGHT:-0.5}"
ADAPTIVE_TRANSITION_GATE_ADJACENT="${ADAPTIVE_TRANSITION_GATE_ADJACENT:-1}"
ADAPTIVE_TRANSITION_GATE_PAGE_DOC="${ADAPTIVE_TRANSITION_GATE_PAGE_DOC:-1}"
ADAPTIVE_TRANSITION_GATE_PAGE_TO_DOC="${ADAPTIVE_TRANSITION_GATE_PAGE_TO_DOC:-1}"
ADAPTIVE_TRANSITION_GATE_DOC_TO_PAGE="${ADAPTIVE_TRANSITION_GATE_DOC_TO_PAGE:-1}"
ADAPTIVE_ADJACENT_MODE="${ADAPTIVE_ADJACENT_MODE:-none}"
ADAPTIVE_ADJACENT_MIN_MULT="${ADAPTIVE_ADJACENT_MIN_MULT:-0.0}"
ADAPTIVE_ADJACENT_MAX_MULT="${ADAPTIVE_ADJACENT_MAX_MULT:-1.0}"
ADAPTIVE_ADJACENT_POWER="${ADAPTIVE_ADJACENT_POWER:-0.5}"
EVIDENCE_COMMUNITY_MODE="${EVIDENCE_COMMUNITY_MODE:-none}"
EVIDENCE_COMMUNITY_SOURCE_EDGE_WEIGHT="${EVIDENCE_COMMUNITY_SOURCE_EDGE_WEIGHT:-0.25}"
EVIDENCE_COMMUNITY_LOCAL_EDGE_WEIGHT="${EVIDENCE_COMMUNITY_LOCAL_EDGE_WEIGHT:-0.25}"
EVIDENCE_COMMUNITY_MIN_PAGE_SUPPORT="${EVIDENCE_COMMUNITY_MIN_PAGE_SUPPORT:-0.05}"
EVIDENCE_COMMUNITY_LOCAL_WINDOW="${EVIDENCE_COMMUNITY_LOCAL_WINDOW:-2}"
EVIDENCE_COMMUNITY_BOTH_SOURCE_BONUS="${EVIDENCE_COMMUNITY_BOTH_SOURCE_BONUS:-0.10}"
EVIDENCE_COMMUNITY_SUPPORT_POWER="${EVIDENCE_COMMUNITY_SUPPORT_POWER:-1.0}"
DOC_PAGES_JSONL="${DOC_PAGES_JSONL:-$DATA_ROOT/doc_pages_${SPLIT}.jsonl}"
POSITION_EVIDENCE_MODE="${POSITION_EVIDENCE_MODE:-none}"
POSITION_EVIDENCE_EDGE_WEIGHT="${POSITION_EVIDENCE_EDGE_WEIGHT:-0.10}"
POSITION_EVIDENCE_RESTART_WEIGHT="${POSITION_EVIDENCE_RESTART_WEIGHT:-0.10}"
POSITION_EVIDENCE_EXPLICIT_PAGE_EDGE_WEIGHT="${POSITION_EVIDENCE_EXPLICIT_PAGE_EDGE_WEIGHT:-0.50}"
POSITION_EVIDENCE_EXPLICIT_PAGE_RESTART_WEIGHT="${POSITION_EVIDENCE_EXPLICIT_PAGE_RESTART_WEIGHT:-0.25}"
POSITION_EVIDENCE_EARLY_FRAC="${POSITION_EVIDENCE_EARLY_FRAC:-0.15}"
POSITION_EVIDENCE_LATE_FRAC="${POSITION_EVIDENCE_LATE_FRAC:-0.15}"
DOC_SEED_WEIGHT="${DOC_SEED_WEIGHT:-0.0}"
RESTART_PROB="${RESTART_PROB:-$DEFAULT_RESTART_PROB}"
PPR_ITERS="${PPR_ITERS:-30}"
PAGE_DOC_EDGE_WEIGHT="${PAGE_DOC_EDGE_WEIGHT:-1.0}"
PAGE_TO_DOC_EDGE_WEIGHT="${PAGE_TO_DOC_EDGE_WEIGHT:-$PAGE_DOC_EDGE_WEIGHT}"
DOC_TO_PAGE_EDGE_WEIGHT="${DOC_TO_PAGE_EDGE_WEIGHT:-$PAGE_DOC_EDGE_WEIGHT}"
ADJACENT_PAGE_EDGE_WEIGHT="${ADJACENT_PAGE_EDGE_WEIGHT:-0.25}"
SAME_DOC_WINDOW="${SAME_DOC_WINDOW:-1}"
FINAL_PAGE_SEED_WEIGHT="${FINAL_PAGE_SEED_WEIGHT:-1.0}"
FINAL_PPR_PAGE_WEIGHT="${FINAL_PPR_PAGE_WEIGHT:-1.5}"
FINAL_PPR_DOC_WEIGHT="${FINAL_PPR_DOC_WEIGHT:-$DEFAULT_FINAL_PPR_DOC_WEIGHT}"

SPLADE_INDEX_PT="${SPLADE_INDEX_PT:-}"
EXPANSION_TOP_PAGES="${EXPANSION_TOP_PAGES:-0}"
EXPAND_FROM_TOP_DENSE_PAGES="${EXPAND_FROM_TOP_DENSE_PAGES:-50}"
EXPAND_FROM_TOP_SPARSE_PAGES="${EXPAND_FROM_TOP_SPARSE_PAGES:-50}"
EXPANSION_WEIGHT="${EXPANSION_WEIGHT:-1.0}"
EXPANSION_SOURCE_TERM_TOPK="${EXPANSION_SOURCE_TERM_TOPK:-32}"
EXPANSION_QUERY_TOPK_TERMS="${EXPANSION_QUERY_TOPK_TERMS:-256}"
EXPANSION_MIN_SCORE="${EXPANSION_MIN_SCORE:-0.0}"
NEIGHBOR_EXPANSION_WINDOW="${NEIGHBOR_EXPANSION_WINDOW:-0}"
EXPAND_NEIGHBORS_FROM_TOP_DENSE_PAGES="${EXPAND_NEIGHBORS_FROM_TOP_DENSE_PAGES:-50}"
EXPAND_NEIGHBORS_FROM_TOP_SPARSE_PAGES="${EXPAND_NEIGHBORS_FROM_TOP_SPARSE_PAGES:-50}"
NEIGHBOR_SEED_WEIGHT="${NEIGHBOR_SEED_WEIGHT:-0.25}"
SCORE_SEED_WEIGHT="${SCORE_SEED_WEIGHT:-0.0}"
QUESTION_TYPE="${QUESTION_TYPE:-}"
RECALL_K_VALUES="${RECALL_K_VALUES:-$DEFAULT_RECALL_K_VALUES}"

mkdir -p "$OUT_DIR"

GRAPH_ARGS=(
  --dense-prediction-json "$DENSE_PRED"
  --sparse-prediction-json "$SPARSE_PRED"
  --gold "$GOLD"
  --dense-top-pages "$DENSE_TOP_PAGES"
  --sparse-top-pages "$SPARSE_TOP_PAGES"
  --final-top-pages "$FINAL_TOP_PAGES"
  --per-doc-page-limit "$PER_DOC_PAGE_LIMIT"
  --rrf-k "$RRF_K"
  --dense-weight "$DENSE_WEIGHT"
  --sparse-weight "$SPARSE_WEIGHT"
  --adaptive-source-weight-mode "$ADAPTIVE_SOURCE_WEIGHT_MODE"
  --adaptive-source-agreement-top-pages "$ADAPTIVE_SOURCE_AGREEMENT_TOP_PAGES"
  --adaptive-source-top1-lookup-pages "$ADAPTIVE_SOURCE_TOP1_LOOKUP_PAGES"
  --adaptive-source-doc-overlap-weight "$ADAPTIVE_SOURCE_DOC_OVERLAP_WEIGHT"
  --adaptive-source-page-overlap-weight "$ADAPTIVE_SOURCE_PAGE_OVERLAP_WEIGHT"
  --adaptive-source-top1-weight "$ADAPTIVE_SOURCE_TOP1_WEIGHT"
  --adaptive-source-strength "$ADAPTIVE_SOURCE_STRENGTH"
  --adaptive-source-gamma "$ADAPTIVE_SOURCE_GAMMA"
  --adaptive-source-min-dense-mult "$ADAPTIVE_SOURCE_MIN_DENSE_MULT"
  --adaptive-source-max-dense-mult "$ADAPTIVE_SOURCE_MAX_DENSE_MULT"
  --adaptive-source-min-sparse-mult "$ADAPTIVE_SOURCE_MIN_SPARSE_MULT"
  --adaptive-source-max-sparse-mult "$ADAPTIVE_SOURCE_MAX_SPARSE_MULT"
  --adaptive-source-reciprocal-top-pages "$ADAPTIVE_SOURCE_RECIPROCAL_TOP_PAGES"
  --adaptive-source-reciprocal-lookup-pages "$ADAPTIVE_SOURCE_RECIPROCAL_LOOKUP_PAGES"
  --adaptive-source-reciprocal-doc-weight "$ADAPTIVE_SOURCE_RECIPROCAL_DOC_WEIGHT"
  --adaptive-source-reciprocal-page-weight "$ADAPTIVE_SOURCE_RECIPROCAL_PAGE_WEIGHT"
  --adaptive-source-reciprocal-min-mult "$ADAPTIVE_SOURCE_RECIPROCAL_MIN_MULT"
  --adaptive-source-reciprocal-max-mult "$ADAPTIVE_SOURCE_RECIPROCAL_MAX_MULT"
  --adaptive-restart-mode "$ADAPTIVE_RESTART_MODE"
  --adaptive-restart-source-strength "$ADAPTIVE_RESTART_SOURCE_STRENGTH"
  --adaptive-restart-gamma "$ADAPTIVE_RESTART_GAMMA"
  --adaptive-restart-min-dense-mult "$ADAPTIVE_RESTART_MIN_DENSE_MULT"
  --adaptive-restart-max-dense-mult "$ADAPTIVE_RESTART_MAX_DENSE_MULT"
  --adaptive-restart-min-sparse-mult "$ADAPTIVE_RESTART_MIN_SPARSE_MULT"
  --adaptive-restart-max-sparse-mult "$ADAPTIVE_RESTART_MAX_SPARSE_MULT"
  --adaptive-restart-page-seed-weight "$ADAPTIVE_RESTART_PAGE_SEED_WEIGHT"
  --adaptive-restart-doc-seed-weight "$ADAPTIVE_RESTART_DOC_SEED_WEIGHT"
  --adaptive-restart-min-doc-mult "$ADAPTIVE_RESTART_MIN_DOC_MULT"
  --adaptive-restart-max-doc-mult "$ADAPTIVE_RESTART_MAX_DOC_MULT"
  --adaptive-restart-neighbor-seed-weight "$ADAPTIVE_RESTART_NEIGHBOR_SEED_WEIGHT"
  --adaptive-transition-mode "$ADAPTIVE_TRANSITION_MODE"
  --adaptive-transition-agreement-min-mult "$ADAPTIVE_TRANSITION_AGREEMENT_MIN_MULT"
  --adaptive-transition-agreement-max-mult "$ADAPTIVE_TRANSITION_AGREEMENT_MAX_MULT"
  --adaptive-transition-local-min-mult "$ADAPTIVE_TRANSITION_LOCAL_MIN_MULT"
  --adaptive-transition-local-max-mult "$ADAPTIVE_TRANSITION_LOCAL_MAX_MULT"
  --adaptive-transition-local-weight "$ADAPTIVE_TRANSITION_LOCAL_WEIGHT"
  --adaptive-adjacent-mode "$ADAPTIVE_ADJACENT_MODE"
  --adaptive-adjacent-min-mult "$ADAPTIVE_ADJACENT_MIN_MULT"
  --adaptive-adjacent-max-mult "$ADAPTIVE_ADJACENT_MAX_MULT"
  --adaptive-adjacent-power "$ADAPTIVE_ADJACENT_POWER"
  --evidence-community-mode "$EVIDENCE_COMMUNITY_MODE"
  --evidence-community-source-edge-weight "$EVIDENCE_COMMUNITY_SOURCE_EDGE_WEIGHT"
  --evidence-community-local-edge-weight "$EVIDENCE_COMMUNITY_LOCAL_EDGE_WEIGHT"
  --evidence-community-min-page-support "$EVIDENCE_COMMUNITY_MIN_PAGE_SUPPORT"
  --evidence-community-local-window "$EVIDENCE_COMMUNITY_LOCAL_WINDOW"
  --evidence-community-both-source-bonus "$EVIDENCE_COMMUNITY_BOTH_SOURCE_BONUS"
  --evidence-community-support-power "$EVIDENCE_COMMUNITY_SUPPORT_POWER"
  --position-evidence-mode "$POSITION_EVIDENCE_MODE"
  --position-evidence-edge-weight "$POSITION_EVIDENCE_EDGE_WEIGHT"
  --position-evidence-restart-weight "$POSITION_EVIDENCE_RESTART_WEIGHT"
  --position-evidence-explicit-page-edge-weight "$POSITION_EVIDENCE_EXPLICIT_PAGE_EDGE_WEIGHT"
  --position-evidence-explicit-page-restart-weight "$POSITION_EVIDENCE_EXPLICIT_PAGE_RESTART_WEIGHT"
  --position-evidence-early-frac "$POSITION_EVIDENCE_EARLY_FRAC"
  --position-evidence-late-frac "$POSITION_EVIDENCE_LATE_FRAC"
  --doc-seed-weight "$DOC_SEED_WEIGHT"
  --restart-prob "$RESTART_PROB"
  --ppr-iters "$PPR_ITERS"
  --page-doc-edge-weight "$PAGE_DOC_EDGE_WEIGHT"
  --page-to-doc-edge-weight "$PAGE_TO_DOC_EDGE_WEIGHT"
  --doc-to-page-edge-weight "$DOC_TO_PAGE_EDGE_WEIGHT"
  --adjacent-page-edge-weight "$ADJACENT_PAGE_EDGE_WEIGHT"
  --same-doc-window "$SAME_DOC_WINDOW"
  --final-page-seed-weight "$FINAL_PAGE_SEED_WEIGHT"
  --final-ppr-page-weight "$FINAL_PPR_PAGE_WEIGHT"
  --final-ppr-doc-weight "$FINAL_PPR_DOC_WEIGHT"
  --score-seed-weight "$SCORE_SEED_WEIGHT"
  --expansion-top-pages "$EXPANSION_TOP_PAGES"
  --expand-from-top-dense-pages "$EXPAND_FROM_TOP_DENSE_PAGES"
  --expand-from-top-sparse-pages "$EXPAND_FROM_TOP_SPARSE_PAGES"
  --expansion-weight "$EXPANSION_WEIGHT"
  --expansion-source-term-topk "$EXPANSION_SOURCE_TERM_TOPK"
  --expansion-query-topk-terms "$EXPANSION_QUERY_TOPK_TERMS"
  --expansion-min-score "$EXPANSION_MIN_SCORE"
  --output-prediction-json "$PRED_OUT"
  --output-summary-json "$SUMMARY_OUT"
)
if [[ "$ADAPTIVE_SOURCE_RECIPROCAL_PRESERVE_TOTAL" == "0" ]]; then
  GRAPH_ARGS+=(--no-adaptive-source-reciprocal-preserve-total)
else
  GRAPH_ARGS+=(--adaptive-source-reciprocal-preserve-total)
fi
if [[ "$ADAPTIVE_RESTART_PRESERVE_SOURCE_TOTAL" == "0" ]]; then
  GRAPH_ARGS+=(--no-adaptive-restart-preserve-source-total)
else
  GRAPH_ARGS+=(--adaptive-restart-preserve-source-total)
fi
if [[ "$ADAPTIVE_TRANSITION_GATE_ADJACENT" == "0" ]]; then
  GRAPH_ARGS+=(--no-adaptive-transition-gate-adjacent)
else
  GRAPH_ARGS+=(--adaptive-transition-gate-adjacent)
fi
if [[ "$ADAPTIVE_TRANSITION_GATE_PAGE_DOC" == "0" ]]; then
  GRAPH_ARGS+=(--no-adaptive-transition-gate-page-doc)
else
  GRAPH_ARGS+=(--adaptive-transition-gate-page-doc)
fi
if [[ "$ADAPTIVE_TRANSITION_GATE_PAGE_TO_DOC" == "0" ]]; then
  GRAPH_ARGS+=(--no-adaptive-transition-gate-page-to-doc)
else
  GRAPH_ARGS+=(--adaptive-transition-gate-page-to-doc)
fi
if [[ "$ADAPTIVE_TRANSITION_GATE_DOC_TO_PAGE" == "0" ]]; then
  GRAPH_ARGS+=(--no-adaptive-transition-gate-doc-to-page)
else
  GRAPH_ARGS+=(--adaptive-transition-gate-doc-to-page)
fi
if [[ -n "$DOC_PAGES_JSONL" && -f "$DOC_PAGES_JSONL" ]]; then
  GRAPH_ARGS+=(--doc-pages-jsonl "$DOC_PAGES_JSONL")
fi
if [[ -n "$QUESTION_TYPE" ]]; then
  GRAPH_ARGS+=(--question-type "$QUESTION_TYPE")
fi
if [[ -n "$SPLADE_INDEX_PT" ]]; then
  GRAPH_ARGS+=(--splade-index-pt "$SPLADE_INDEX_PT")
fi
if [[ "$NEIGHBOR_EXPANSION_WINDOW" -gt 0 ]]; then
  GRAPH_ARGS+=(
    --neighbor-expansion-window "$NEIGHBOR_EXPANSION_WINDOW"
    --neighbor-seed-weight "$NEIGHBOR_SEED_WEIGHT"
    --expand-neighbors-from-top-dense-pages "$EXPAND_NEIGHBORS_FROM_TOP_DENSE_PAGES"
    --expand-neighbors-from-top-sparse-pages "$EXPAND_NEIGHBORS_FROM_TOP_SPARSE_PAGES"
  )
fi

"$PYTHON_BIN" "$REPO_ROOT/scripts/graph_rerank_page_retrieval_predictions.py" "${GRAPH_ARGS[@]}"

read -r -a RECALL_K_ARRAY <<< "$RECALL_K_VALUES"
"$PYTHON_BIN" "$REPO_ROOT/mmdocir/evaluate_mmdocir_retrieval.py" \
  --pred "$PRED_OUT" \
  --gold "$GOLD" \
  --recall-k "${RECALL_K_ARRAY[@]}"
